import { useState } from "react";
import type { StrategyRecommendation, StrategyEntry } from "../lib/types";

interface SelectedEntry {
  phase: StrategyRecommendation["phase"];
  label: string;
  entry: StrategyEntry;
}

interface SubmissionPlanProps {
  selectedEntries: SelectedEntry[];
  onBack: () => void;
}

const PHASE_ORDER: StrategyRecommendation["phase"][] = [
  "world_premiere",
  "international_premiere",
  "national_premiere",
  "open",
];

const PHASE_LABELS: Record<StrategyRecommendation["phase"], string> = {
  world_premiere: "World Premiere",
  international_premiere: "International Premiere",
  national_premiere: "National Premiere",
  open: "No Premiere Requirement",
};

const PHASE_COLORS: Record<StrategyRecommendation["phase"], { dot: string; line: string; bg: string; text: string }> = {
  world_premiere: { dot: "bg-red-400", line: "bg-red-500/30", bg: "bg-red-500/10", text: "text-red-300" },
  international_premiere: { dot: "bg-orange-400", line: "bg-orange-500/30", bg: "bg-orange-500/10", text: "text-orange-300" },
  national_premiere: { dot: "bg-yellow-400", line: "bg-yellow-500/30", bg: "bg-yellow-500/10", text: "text-yellow-300" },
  open: { dot: "bg-emerald-400", line: "bg-emerald-500/30", bg: "bg-emerald-500/10", text: "text-emerald-300" },
};

function formatDate(dateStr: string): string {
  return new Date(dateStr + "T00:00:00").toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

interface TimelineStep {
  type: "submit" | "wait" | "decision" | "parallel_note";
  phase: StrategyRecommendation["phase"];
  festival?: StrategyEntry;
  text: string;
  subtext?: string;
}

function buildTimeline(entries: SelectedEntry[]): TimelineStep[] {
  const steps: TimelineStep[] = [];

  // Group entries by phase, maintaining premiere hierarchy order
  const grouped = new Map<StrategyRecommendation["phase"], SelectedEntry[]>();
  for (const phase of PHASE_ORDER) {
    const phaseEntries = entries.filter((e) => e.phase === phase);
    if (phaseEntries.length > 0) {
      // Sort by deadline within phase
      phaseEntries.sort((a, b) => a.entry.deadline.date.localeCompare(b.entry.deadline.date));
      grouped.set(phase, phaseEntries);
    }
  }

  const phases = Array.from(grouped.keys());

  for (let i = 0; i < phases.length; i++) {
    const phase = phases[i];
    const phaseEntries = grouped.get(phase)!;
    const isOpenPhase = phase === "open";
    const isPremierePhase = !isOpenPhase;

    // For the open phase, add a note that these can be submitted anytime
    if (isOpenPhase) {
      steps.push({
        type: "parallel_note",
        phase,
        text: "Submit anytime — no premiere requirement",
        subtext: "These festivals don't require a premiere status, so you can submit regardless of other results.",
      });
    }

    // Add submit steps for each festival in this phase
    for (const { entry } of phaseEntries) {
      const feeStr = entry.deadline.fee === 0 ? "Free" : `$${entry.deadline.fee}`;
      steps.push({
        type: "submit",
        phase,
        festival: entry,
        text: `Submit to ${entry.festival.name}`,
        subtext: `${entry.deadline.type} deadline: ${formatDate(entry.deadline.date)} · ${feeStr}`,
      });
    }

    // After a premiere phase, add wait + decision steps if there's a next premiere phase
    if (isPremierePhase) {
      // Find the latest notification date in this phase
      const notificationDates = phaseEntries
        .map((e) => e.entry.festival.notificationDate)
        .filter(Boolean) as string[];

      const nextPremierePhase = phases.find(
        (p, idx) => idx > i && p !== "open"
      );

      if (notificationDates.length > 0) {
        const latestNotification = notificationDates.sort().reverse()[0];
        const waitFestivals = phaseEntries
          .filter((e) => e.entry.festival.notificationDate)
          .map((e) => e.entry.festival.name);

        steps.push({
          type: "wait",
          phase,
          text: `Wait for ${waitFestivals.length === 1 ? waitFestivals[0] : "notifications"}`,
          subtext: `Expected by ~${formatDate(latestNotification)}`,
        });
      }

      if (nextPremierePhase) {
        steps.push({
          type: "decision",
          phase,
          text: `If not accepted → proceed to ${PHASE_LABELS[nextPremierePhase].toLowerCase()} targets`,
          subtext: "Your premiere status will be available for the next tier of festivals.",
        });
      }
    }
  }

  return steps;
}

function generatePlanText(entries: SelectedEntry[], steps: TimelineStep[]): string {
  const totalFees = entries.reduce((sum, e) => sum + e.entry.deadline.fee, 0);
  const lines: string[] = [];

  lines.push("FILM FESTIVAL SUBMISSION PLAN");
  lines.push("Generated by FestivalPlanner");
  lines.push("=".repeat(40));
  lines.push("");
  lines.push(`Festivals: ${entries.length}`);
  lines.push(`Est. Total Fees: ${totalFees === 0 ? "Free" : `$${totalFees}`}`);
  lines.push("");
  lines.push("-".repeat(40));
  lines.push("");

  let currentPhase = "";

  for (const step of steps) {
    const phaseName = PHASE_LABELS[step.phase];
    if (phaseName !== currentPhase) {
      currentPhase = phaseName;
      lines.push(`[ ${currentPhase.toUpperCase()} ]`);
      lines.push("");
    }

    if (step.type === "submit" && step.festival) {
      const f = step.festival;
      const feeStr = f.deadline.fee === 0 ? "Free" : `$${f.deadline.fee}`;
      const sourceLabel = f.source.type === "target" ? " [TARGET]"
        : f.source.type === "free_match" ? " [FREE]"
        : f.source.type === "complementary" ? " [SUGGESTED]"
        : "";
      lines.push(`  -> ${f.festival.name}${sourceLabel}`);
      lines.push(`     ${f.festival.location.city}, ${f.festival.location.country} | ${f.festival.tier}`);
      lines.push(`     Deadline: ${formatDate(f.deadline.date)} (${f.deadline.type}) | ${feeStr}`);
      if (f.festival.notificationDate) {
        lines.push(`     Notification: ~${formatDate(f.festival.notificationDate)}`);
      }
      if (f.festival.festivalDates) {
        lines.push(`     Festival: ${formatDate(f.festival.festivalDates.start)} - ${formatDate(f.festival.festivalDates.end)}`);
      }
      lines.push(`     ${f.festival.website}`);
      lines.push("");
    } else if (step.type === "wait") {
      lines.push(`  ⏳ ${step.text}`);
      if (step.subtext) lines.push(`     ${step.subtext}`);
      lines.push("");
    } else if (step.type === "decision") {
      lines.push(`  ⚡ ${step.text}`);
      lines.push("");
    } else if (step.type === "parallel_note") {
      lines.push(`  ℹ ${step.text}`);
      lines.push("");
    }
  }

  lines.push("-".repeat(40));
  lines.push("Always verify deadlines on official festival websites.");
  lines.push("festivalplanner.app");

  return lines.join("\n");
}

export default function SubmissionPlan({ selectedEntries, onBack }: SubmissionPlanProps) {
  const [copied, setCopied] = useState(false);
  const timeline = buildTimeline(selectedEntries);

  const totalFees = selectedEntries.reduce((sum, e) => sum + e.entry.deadline.fee, 0);
  const deadlines = selectedEntries.map((e) => e.entry.deadline.date).sort();
  const earliestDeadline = deadlines[0];
  const latestDeadline = deadlines[deadlines.length - 1];

  // Count by phase
  const premiereCount = selectedEntries.filter((e) => e.phase !== "open").length;
  const openCount = selectedEntries.filter((e) => e.phase === "open").length;

  return (
    <div>
      {/* Header */}
      <div className="bg-film-800/60 rounded-xl border border-film-700/50 p-5 mb-6">
        <div className="flex items-center justify-between mb-4 gap-2">
          <h2 className="text-lg font-semibold text-film-50">
            Your Submission Plan
          </h2>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={() => {
                const text = generatePlanText(selectedEntries, timeline);
                navigator.clipboard.writeText(text).then(() => {
                  setCopied(true);
                  setTimeout(() => setCopied(false), 2000);
                });
              }}
              className={`text-sm px-3 py-1.5 rounded-lg border transition-colors flex items-center gap-1.5 ${
                copied
                  ? "bg-emerald-500/20 border-emerald-500/30 text-emerald-300"
                  : "bg-film-700/50 border-film-600 text-film-300 hover:border-gold-400 hover:text-gold-400"
              }`}
            >
              {copied ? (
                <>
                  <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                  </svg>
                  Copied
                </>
              ) : (
                <>
                  <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                  </svg>
                  Copy plan
                </>
              )}
            </button>
            <button
              type="button"
              onClick={onBack}
              className="text-sm text-film-400 hover:text-gold-400 transition-colors flex items-center gap-1"
            >
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
              </svg>
              Back
            </button>
          </div>
        </div>

        <div className="flex flex-wrap gap-4 sm:gap-6">
          <div>
            <p className="text-xl sm:text-2xl font-bold text-gold-400">{selectedEntries.length}</p>
            <p className="text-xs sm:text-sm text-film-400">Festivals</p>
          </div>
          <div>
            <p className="text-xl sm:text-2xl font-bold text-gold-400">
              {totalFees === 0 ? "Free" : `$${totalFees}`}
            </p>
            <p className="text-xs sm:text-sm text-film-400">Est. total fees</p>
          </div>
          {earliestDeadline && (
            <div>
              <p className="text-xl sm:text-2xl font-bold text-gold-400">
                {formatDate(earliestDeadline).split(",")[0]}
              </p>
              <p className="text-xs sm:text-sm text-film-400">First deadline</p>
            </div>
          )}
        </div>

        {premiereCount > 0 && openCount > 0 && (
          <p className="text-xs text-film-500 mt-3">
            {premiereCount} premiere-tier festival{premiereCount !== 1 ? "s" : ""} (submit in order) · {openCount} open festival{openCount !== 1 ? "s" : ""} (submit anytime)
          </p>
        )}
      </div>

      {/* Timeline */}
      <div className="bg-film-800/60 rounded-xl border border-film-700/50 p-4 sm:p-6">
        <h3 className="text-sm font-semibold text-film-300 uppercase tracking-wider mb-6">
          Step-by-step timeline
        </h3>

        <div className="relative">
          {timeline.map((step, idx) => {
            const colors = PHASE_COLORS[step.phase];
            const isLast = idx === timeline.length - 1;

            return (
              <div key={idx} className="relative flex gap-4 pb-6 last:pb-0">
                {/* Vertical line */}
                {!isLast && (
                  <div
                    className={`absolute left-[11px] top-6 bottom-0 w-0.5 ${
                      step.type === "wait" || step.type === "decision"
                        ? "bg-film-600/50"
                        : colors.line
                    }`}
                  />
                )}

                {/* Dot / icon */}
                <div className="relative shrink-0 z-10">
                  {step.type === "submit" ? (
                    <div className={`w-6 h-6 rounded-full ${colors.dot} flex items-center justify-center`}>
                      <svg className="w-3.5 h-3.5 text-film-950" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
                      </svg>
                    </div>
                  ) : step.type === "wait" ? (
                    <div className="w-6 h-6 rounded-full bg-film-700 border-2 border-film-500 flex items-center justify-center">
                      <svg className="w-3 h-3 text-film-300" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                    </div>
                  ) : step.type === "decision" ? (
                    <div className="w-6 h-6 rounded-full bg-film-700 border-2 border-amber-500/50 flex items-center justify-center">
                      <svg className="w-3 h-3 text-amber-300" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                    </div>
                  ) : (
                    <div className="w-6 h-6 rounded-full bg-emerald-500/20 border-2 border-emerald-400 flex items-center justify-center">
                      <svg className="w-3 h-3 text-emerald-300" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" />
                      </svg>
                    </div>
                  )}
                </div>

                {/* Content */}
                <div className="flex-1 min-w-0 pt-0.5">
                  <p className={`text-sm font-medium ${
                    step.type === "submit" ? "text-film-50" :
                    step.type === "wait" ? "text-film-300" :
                    step.type === "decision" ? "text-amber-300" :
                    colors.text
                  }`}>
                    {step.text}
                  </p>
                  {step.subtext && (
                    <p className="text-xs text-film-500 mt-0.5">{step.subtext}</p>
                  )}

                  {/* Festival card for submit steps */}
                  {step.type === "submit" && step.festival && (
                    <div className={`mt-2 rounded-lg border border-film-700/50 ${colors.bg} px-3 py-2.5`}>
                      <div className="flex items-start justify-between gap-3">
                        <div className="min-w-0">
                          <a
                            href={step.festival.festival.website}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-sm font-medium text-film-50 hover:text-gold-400 transition-colors inline-flex items-center gap-1.5"
                          >
                            {step.festival.festival.name}
                            <svg className="w-3 h-3 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                              <path strokeLinecap="round" strokeLinejoin="round" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                            </svg>
                          </a>
                          <p className="text-xs text-film-400">
                            {step.festival.festival.location.city}, {step.festival.festival.location.country} · {step.festival.festival.tier}
                          </p>
                        </div>
                        <div className="text-right shrink-0">
                          <p className="text-sm font-medium text-gold-400">
                            {step.festival.deadline.fee === 0 ? "Free" : `$${step.festival.deadline.fee}`}
                          </p>
                        </div>
                      </div>
                      {step.festival.festival.notificationDate && (
                        <p className="text-xs text-film-500 mt-1.5">
                          Notification: ~{formatDate(step.festival.festival.notificationDate)}
                        </p>
                      )}
                      {step.festival.festival.festivalDates && (
                        <p className="text-xs text-film-500">
                          Festival: {formatDate(step.festival.festival.festivalDates.start)} – {formatDate(step.festival.festival.festivalDates.end)}
                        </p>
                      )}
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Bottom back button */}
      <div className="mt-6 flex justify-center">
        <button
          type="button"
          onClick={onBack}
          className="px-6 py-2.5 bg-film-800 text-film-300 rounded-lg font-medium text-sm border border-film-600 hover:border-gold-400 hover:text-gold-400 transition-colors"
        >
          Back to festival selection
        </button>
      </div>
    </div>
  );
}
